login_task:
  description: >
    Log into the CRDC QA portal using login.gov. The credentials will be injected at runtime.
  expected_output: >
    A successful login message or URL verification
  agent: login_agent
  input_direct: true

navigate_task:
  description: >
    Navigate to the submission request part of the portal
  expected_output: >
    A successful navigation
  agent: navigate_agent
  input_direct: true

create_submission_task:
  description: >
    Click the button to start a new submission request on the portal.
  expected_output: >
    A submission form page should be displayed.
  agent: create_sr_agent